In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv(
    "../data/olist_customers_dataset.csv"
)

customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [3]:
customers.shape

(99441, 5)

In [4]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [5]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [6]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [7]:
orders = pd.read_csv(
    "../data/olist_orders_dataset.csv"
)

order_items = pd.read_csv(
    "../data/olist_order_items_dataset.csv"
)

products = pd.read_csv(
    "../data/olist_products_dataset.csv"
)

payments = pd.read_csv(
    "../data/olist_order_payments_dataset.csv"
)

reviews = pd.read_csv(
    "../data/olist_order_reviews_dataset.csv"
)

sellers = pd.read_csv(
    "../data/olist_sellers_dataset.csv"
)

geolocation = pd.read_csv(
    "../data/olist_geolocation_dataset.csv"
)

translation = pd.read_csv(
    "../data/product_category_name_translation.csv"
)

In [8]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Sellers:", sellers.shape)
print("Geolocation:", geolocation.shape)
print("Translation:", translation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)
Reviews: (99224, 7)
Sellers: (3095, 4)
Geolocation: (1000163, 5)
Translation: (71, 2)

In [9]:
# Display the columns in each dataset

datasets = {
    "Customers": customers,
    "Orders": orders,
    "Order Items": order_items,
    "Products": products,
    "Payments": payments,
    "Reviews": reviews,
    "Sellers": sellers,
    "Geolocation": geolocation,
    "Translation": translation
}

for name, data in datasets.items():
    print(f"\n{name}")
    print("-" * 50)
    print(list(data.columns))

Customers
--------------------------------------------------
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Orders
--------------------------------------------------
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Order Items
--------------------------------------------------
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Products
--------------------------------------------------
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Payments
--------------------------------------------------
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Reviews
--------------------------------------------------
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Sellers
--------------------------------------------------
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Geolocation
--------------------------------------------------
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Translation
--------------------------------------------------
['product_category_name', 'product_category_name_english']

In [10]:
for name, data in datasets.items():
    print(f"\n{name}")
    print("=" * 60)
    print("Rows:", len(data))
    print("Columns:", len(data.columns))
    print("Duplicate rows:", data.duplicated().sum())
    print("Missing values:", data.isnull().sum().sum())

Customers
============================================================
Rows: 99441
Columns: 5
Duplicate rows: 0
Missing values: 0

Orders
============================================================
Rows: 99441
Columns: 8
Duplicate rows: 0
Missing values: 4908

Order Items
============================================================
Rows: 112650
Columns: 7
Duplicate rows: 0
Missing values: 0

Products
============================================================
Rows: 32951
Columns: 9
Duplicate rows: 0
Missing values: 2448

Payments
============================================================
Rows: 103886
Columns: 5
Duplicate rows: 0
Missing values: 0

Reviews
============================================================
Rows: 99224
Columns: 7
Duplicate rows: 0
Missing values: 145903

Sellers
============================================================
Rows: 3095
Columns: 4
Duplicate rows: 0
Missing values: 0

Geolocation
============================================================
Rows: 1000163
Columns: 5
Duplicate rows: 261831
Missing values: 0

Translation
============================================================
Rows: 71
Columns: 2
Duplicate rows: 0
Missing values: 0

In [11]:
for name, data in datasets.items():
    missing = data.isnull().sum()
    missing = missing[missing > 0]

    print(f"\n{name}")
    print("-" * 50)

    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing)

Customers
--------------------------------------------------
No missing values

Orders
--------------------------------------------------
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

Order Items
--------------------------------------------------
No missing values

Products
--------------------------------------------------
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Payments
--------------------------------------------------
No missing values

Reviews
--------------------------------------------------
review_comment_title      87656
review_comment_message    58247
dtype: int64

Sellers
--------------------------------------------------
No missing values

Geolocation
--------------------------------------------------
No missing values

Translation
--------------------------------------------------
No missing values

In [13]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [14]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [15]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [16]:
orders[
    [
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [17]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [18]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for column in date_columns:
    orders[column] = pd.to_datetime(orders[column])

In [19]:
orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [20]:
orders["delivery_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_purchase_timestamp"]
).dt.days

In [21]:
orders["delivery_days"].describe()

count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: delivery_days, dtype: float64

In [22]:
orders["delivery_delay_days"] = (
    orders["order_delivered_customer_date"]
    - orders["order_estimated_delivery_date"]
).dt.days

In [23]:
orders["delivery_delay_days"].describe()

count    96476.000000
mean       -11.876881
std         10.183854
min       -147.000000
25%        -17.000000
50%        -12.000000
75%         -7.000000
max        188.000000
Name: delivery_delay_days, dtype: float64

In [24]:
orders["delivery_delay_days"].value_counts().head(20)

delivery_delay_days
-14.0    7126
-13.0    5963
-15.0    5345
-7.0     4837
-8.0     4828
-10.0    4646
-9.0     4626
-11.0    4619
-12.0    4556
-16.0    3903
-6.0     3625
-17.0    3412
-18.0    3128
-20.0    2960
-21.0    2810
-19.0    2712
-5.0     2219
-4.0     1917
-22.0    1845
-3.0     1731
Name: count, dtype: int64

In [25]:
print("Total orders:", len(orders))

print(
    "Orders with delivery date:",
    orders["order_delivered_customer_date"].notna().sum()
)

print(
    "Orders without delivery date:",
    orders["order_delivered_customer_date"].isna().sum()
)

Total orders: 99441
Orders with delivery date: 96476
Orders without delivery date: 2965

In [26]:
delivered_orders = orders[
    orders["order_delivered_customer_date"].notna()
].copy()

on_time_orders = delivered_orders[
    delivered_orders["delivery_delay_days"] <= 0
]

late_orders = delivered_orders[
    delivered_orders["delivery_delay_days"] > 0
]

print("Delivered orders:", len(delivered_orders))
print("On-time orders:", len(on_time_orders))
print("Late orders:", len(late_orders))

print(
    "On-time delivery rate:",
    round(len(on_time_orders) / len(delivered_orders) * 100, 2),
    "%"
)

print(
    "Late delivery rate:",
    round(len(late_orders) / len(delivered_orders) * 100, 2),
    "%"
)

Delivered orders: 96476
On-time orders: 89941
Late orders: 6535
On-time delivery rate: 93.23 %
Late delivery rate: 6.77 %

# 2. Data Quality Assessment

Before performing business analysis, the datasets are checked for:

- Missing values
- Duplicate records
- Invalid or inconsistent values
- Incorrect data types
- Outliers
- Referential integrity between tables

The purpose is to ensure that subsequent analysis and business insights are based on reliable data.

In [27]:
missing_summary = []

for name, data in datasets.items():
    for column in data.columns:
        missing_count = data[column].isna().sum()
        missing_pct = (missing_count / len(data)) * 100

        if missing_count > 0:
            missing_summary.append({
                "Dataset": name,
                "Column": column,
                "Missing Values": missing_count,
                "Missing %": round(missing_pct, 2)
            })

missing_df = pd.DataFrame(missing_summary)

missing_df.sort_values(
    "Missing %",
    ascending=False
)

     Dataset                         Column  Missing Values  Missing %
13   Reviews           review_comment_title           87656      88.34
14   Reviews         review_comment_message           58247      58.70
2     Orders  order_delivered_customer_date            2965       2.98
3     Orders                  delivery_days            2965       2.98
4     Orders            delivery_delay_days            2965       2.98
5   Products          product_category_name             610       1.85
6   Products            product_name_lenght             610       1.85
7   Products     product_description_lenght             610       1.85
8   Products             product_photos_qty             610       1.85
1     Orders   order_delivered_carrier_date            1783       1.79
0     Orders              order_approved_at             160       0.16
9   Products               product_weight_g               2       0.01
10  Products              product_length_cm               2       0.01
11  Products              product_height_cm               2       0.01
12  Products               product_width_cm               2       0.01

In [28]:
duplicate_summary = []

for name, data in datasets.items():
    duplicate_summary.append({
        "Dataset": name,
        "Duplicate Rows": data.duplicated().sum()
    })

duplicates_df = pd.DataFrame(duplicate_summary)

duplicates_df

       Dataset  Duplicate Rows
0    Customers               0
1       Orders               0
2  Order Items               0
3     Products               0
4     Payments               0
5      Reviews               0
6      Sellers               0
7  Geolocation          261831
8  Translation               0

In [29]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64